### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by wermaxta** [EgeBalci/HERCULES#3]
HI i have problem with HERCULES
When i type go run HERCULES.go or go build HERCULES.go i get this message 
HERCULES.go:13:8: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go-1.6/src/github.com/fatih/color (from $GOROOT)
	($GOPATH not set)

My OS is Linux kali 4.5.0-kali1-amd64 #1 SMP Debian 4.5.5-1kali1 (2016-06-06) x86_64 GNU/Linux

**Comment by EgeBalci** [comment]
Hi, inorder to run HERCULES from source code you need to get color package for golang you can get the package with "export GOPATH=$HOME && go get github.com/fatih/color" command, also you can run HERCULES directly with binarys, the only reason i upload the binarys is for avoiding these kind of errors ;D

**Comment by joakinmax** [comment]
hi EgeBalci i have a problem too look what happen when i try tu compiling


[*] export GOOS=windows && export GOARCH=386 && go build -ldflags "-H windowsgui -s -w" maxrep.go
maxrep.go:7:8: cannot find package "EGESPLOIT/RSE" in any of:
	/usr/local/go/src/EGESPLOIT/RSE (from $GOROOT)
	/root/src/EGESPLOIT/RSE (from $GOPATH)

[!] ERROR : Compile failed

**Comment by wirehack7** [comment]
```
git clone https://github.com/EgeBalci/EGESPLOIT.git
cp -R EGESPLOIT/ /usr/local/go/src/
```
Tested on Kali, works.
```
# cat /etc/issue
Kali GNU/Linux Rolling \n \l

 ██░ ██ ▓█████  ██▀███   ▄████▄   █    ██  ██▓    ▓█████   ██████ 
▓██░ ██▒▓█   ▀ ▓██ ▒ ██▒▒██▀ ▀█   ██  ▓██▒▓██▒    ▓█   ▀ ▒██    ▒ 
▒██▀▀██░▒███   ▓██ ░▄█ ▒▒▓█    ▄ ▓██  ▒██░▒██░    ▒███   ░ ▓██▄   
░▓█ ░██ ▒▓█  ▄ ▒██▀▀█▄  ▒▓▓▄ ▄██▒▓▓█  ░██░▒██░    ▒▓█  ▄   ▒   ██▒
░▓█▒░██▓░▒████▒░██▓ ▒██▒▒ ▓███▀ ░▒▒█████▓ ░██████▒░▒████▒▒██████▒▒
 ▒ ░░▒░▒░░ ▒░ ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░░▒▓▒ ▒ ▒ ░ ▒░▓  ░░░ ▒░ ░▒ ▒▓▒ ▒ ░
 ▒ ░▒░ ░ ░ ░  ░  ░▒ ░ ▒░  ░  ▒   ░░▒░ ░ ░ ░ ░ ▒  ░ ░ ░  ░░ ░▒  ░ ░
 ░  ░░ ░   ░     ░░   ░ ░         ░░░ ░ ░   ░ ░      ░   ░  ░  ░  
 ░  ░  ░   ░  ░   ░     ░ ░         ░         ░  ░   ░  ░      ░  
                        ░                                         
#====================================================================================#
#     SELECTED PAYLOAD                       |     SIZE/UPX     |  AV Evasion Score  #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|~~~~~~~~~~~~~~~~~~|~~~~~~~~~~~~~~~~~~~~#
# Meterpreter Reverse TCP                    | 946 KB / 262 KB  |        4/10        #
#====================================================================================#

[*] Persistence : ON (-2)

[*] Migration : ON (-1)

[*] UPX : ON (-3)

[*] Payload Size : 326 KB

[*] Payload saved at : /$HOME/malware.exe

```

**Comment by Rishab2** [comment]
i keep getting this error after when i use the AV Bypass Function

command-line-arguments
./Test.go:7: imported and not used: "EGESPLOIT/RSE"

Anyone can assist me with this i tried all possible solutions.

Thank You

**Comment by EgeBalci** [comment]
I just pushed a patch for this issue, simply clone the latest release to another folder and reinstall  it with Setup.go it should be ok.

**Comment by Rishab2** [comment]
Thanks man thats was really fast :-)

**Comment by Rishab2** [comment]
Im still getting the same error!!! :(

[*] Compiling payload...

[*] export GOOS=windows && export GOARCH=386 && export GOPATH=$HERCULES_PATH && go build -ldflags "-H windowsgui -s -w" TEST.go
# command-line-arguments
./TEST.go:7: imported and not used: "EGESPLOIT/RSE"

**Comment by EgeBalci** [comment]
You need to remove old hercules installation and clone the latest repo :/

**Comment by Rishab2** [comment]
I have deleted the HERCULES file many times and cloned it.  I get the same error :'(...

**Comment by EgeBalci** [comment]
I have tested the final release in various platforms and it is working well, it seems to me that you are the only one having this issue, manually cloning the EGESPLOIT library may solve this, after opening the HERCULES folder try this `cd src && git clone https://github.com/EgeBalci/EGESPLOIT.git`

**Comment by ph3n0m79** [comment]
I've followed all the instructions as well, even after cloning the EGESPLOIT library manually, I still get the same error:
 
*] Compiling payload...

[*] export GOOS=windows && export GOARCH=386 && export GOPATH=$HERCULES_PATH && go build -ldflags "-H windowsgui -s -w" test.go
# command-line-arguments
./test.go:7: imported and not used: "EGESPLOIT/RSE"

Any help would be appreciated

**Comment by EgeBalci** [comment]
I am avare of this issue it will be fixed on next version.

**Comment by ph3n0m79** [comment]
Thank you very much

**Comment by jrgdiaz** [comment]
I'm still getting the Golang import unused error on Kali how can i fix this?

**Comment by gummyfish** [comment]
I had the same problem with you, and I have solved this problem successfully with simple command below:
1.apt-get install golang
2. apt-get autoremove 
I think it is the old go version's problem, if you both have the new and old version, HERCULES may not work.

**Comment by gummyfish** [comment]
Do you want to add persistence function to payload (y/n) :
choose "n", then it will be compiled successfullly

**Comment by nkokhi** [comment]
Any update on this error? I am one of those who are getting it even after trying what was suggested.

**Comment by joakinmax** [comment]
hi Markus i have a problem and as u are a profetional i would like u to
help me , i need to do mail spoofing

i used to do it with lazy script the number 15 was mail spoof and was well
very very well but now i dont know what happen can u help me pls thx very
very much
